name: CI

on: [push, pull_request]

jobs:
  build:

    timeout-minutes: 600
    runs-on: [self-hosted, linux, X64]
    container:
      image: dynamicdevices/yocto-ci-build:latest
      options: --privileged --platform linux/amd64  -v /dev/net/tun:/dev/net/tun -v /dev/kvm:/dev/kvm
    strategy:
      matrix:
        yocto-version: [master]
        machine: [qemu]
    steps:
    - uses: actions/checkout@v4
    - name: Restore sstate cache
      id: cache-sstate-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          sstate
        key: ${{ matrix.machine }}-${{ matrix.yocto-version }}-sstate
    - name: Move sstate
      run: |
        mkdir -p sstate
        mv sstate sstate-cache

    - name: Run kas on ${{ matrix.machine }} on ${{ matrix.yocto-version }}
      run: |
        export SSTATE_DIR="${PWD}/sstate"
        export SSTATE_MIRRORS="file://.* file://${PWD}/sstate-cache/PATH;downloadfilename=PATH"
        kas build kas/meta-java-${{ matrix.yocto-version }}.yml:kas/machine-${{ matrix.machine }}.yml:kas/ci.yml

    - name: Save sstate cache
      id: cache-sstate-save
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          sstate
        key: ${{ steps.cache-sstate-restore.outputs.cache-primary-key }}
